version: '3'

services: 
  php:
    image: php:7.4-fpm
    volumes:
      - ./:/var/www
    environment:
      DB_PORT: 3306
      DB_HOST: mysql

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    depends_on:
      - mysql
    volumes:
      - ./nginx/:/etc/nginx/conf.d/:ro
      - ./:/var/www

  mysql:
    image: mysql:8
    volumes: 
      - ./mysql/:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: topSecret

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_PORT=3306
      